config/routes.rb
Rails.application.routes.draw do

  root to: 'geomancer#index'
  constraints(question_id: /[1-9]|1[0-9]|2[0-5]/) do
    get '/:question_id/', to: 'geomancer#question'
    constraints(rolls: /[1-4]{16}/) do
      get '/:question_id/:rolls',   to: 'geomancer#result'
      post '/:question_id/:rolls',  to: 'geomancer#create'
    end
  end
  
  scope '/about' do
    get '/:slug', to: 'static#pages', as: 'topic'
  end

  scope '/admin' do
    resources :pages
    resources :questions, only: [:index, :show] do  
      member do
        get 'lock'
      end
    end
    resources :tags, only: [:create, :update, :destroy]
    resources :transcriptions,  only: [:edit, :index, :show, :update] do
      member do
        get 'lock'
      end
    end
    resources :submissions, only: [:create, :index, :destroy] do
      member do
        get 'select'
      end
    end
    resources :users, only: [:new, :create, :index, :destroy, :edit, :update]
  end

  get    '/about',  to: 'static#about'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :tags, dependent: :destroy
  has_many :resources
end

app/models/pattern.rb
class Pattern < ApplicationRecord
	has_many :transcriptions
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :transcriptions

	def status
		if ENV["BOF_MODE"] != "CROWD_SOURCE" then
			return "Frozen"
		elsif self.locked then
			return "Unfreeze"
		else
			return "Freeze"
		end
	end

	def submissions_allowed?
		if ENV["BOF_MODE"] == "CROWD_SOURCE"  && !self.locked then
			return true
		end
		return false
	end

	def toggle
		if ENV["BOF_MODE"] == "CROWD_SOURCE" then
			self.locked = !self.locked
		end
	end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :transcription
  
  self.per_page = 10

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :transcription
  belongs_to :page

  validates_uniqueness_of :page_id, scope: :transcription_id
end

app/models/transcription.rb
class Transcription < ApplicationRecord
  belongs_to :question
  belongs_to :pattern
  has_many :submissions
  has_many :tags

  accepts_nested_attributes_for :tags, :reject_if => lambda { |a| a[:page_id].blank? }

  self.per_page = 16

  def get_image_url
    aws_link = "https://s3.amazonaws.com/book-of-fate/images/answers";
    q = (self.question.id - 1).to_s.rjust(2, "0");
    p = self.pattern
    return aws_link + "/q" + q + "/q" + q + "_p" + p.page + "_" + p.side + "_" + p.offset + ".jpg"
  end

  def status
    if !self.question.submissions_allowed? then
      return "Frozen"
    elsif self.locked then
      return "Unfreeze"
    else
      return "Freeze"
    end
  end

  def submissions_allowed?
    return self.question.submissions_allowed? && !self.locked
  end

  def toggle
    if self.question.submissions_allowed? then
      self.locked = !self.locked
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :logged_in_user
    layout "admin"

  private

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

end

app/controllers/tags_controller.rb
class TagsController < AdminController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_back(fallback_location: root_path)
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        redirect_to @tag, notice: 'Tag was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:transcription_id, :page_id)
    end
end

app/controllers/transcriptions_controller.rb
class TranscriptionsController < AdminController
  before_action :set_transcription, only: [:show, :edit, :update, :lock]

  # GET /transcriptions
  def index
    @transcriptions = Transcription.paginate(page: params[:page])
  end

  # GET /transcriptions/1
  def show
  end

  # GET /transcriptions/1/edit
  def edit
    3.times { @transcription.tags.build }
  end

  # PATCH/PUT /transcriptions/1
  def update
    if @transcription.update(transcription_params)
      redirect_to @transcription, notice: 'Transcription was successfully updated.'
    else
      render :edit 
    end
  end

  def lock
    @transcription.toggle
    @transcription.save
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transcription
      @transcription = Transcription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transcription_params
      params.require(:transcription).permit(:transcription, :locked, tags_attributes: [:id, :page_id])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geomancer_helper.rb
module GeomancerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/transcriptions_helper.rb
module TranscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/transcriptions/_form.html.erb
<%= form_for(transcription) do |f| %>
  <% if transcription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transcription.errors.count, "error") %> prohibited this transcription from being saved:</h2>

      <ul>
      <% transcription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="margin-bottom: 5px">
    <%= f.text_area :transcription, size: "20x5", class: 'form-control' %>
  </div>

  <br>

  <div class="row">
    <div class="col-md-9">
    <table class="table table-striped">
      <tbody>
        <%= render @transcription.submissions%>
      </tbody>
    </table>
    </div>
    <div class="col-md-3">
      <%= f.fields_for :tags do |builder| %>
        <%= render "tag_fields", f: builder %>
      <% end %>
    </div>
  </div>

  <div class="actions text-center">
    <%= f.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/transcriptions/_tag_fields.html.erb
<p>
  <%= f.collection_select :page_id, Page.order(:title), :id, :title, include_blank: true %>
  <% if f.object.id != nil then %>
  	<%= link_to 'Remove', tag_path(f.object.id),  method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

app/views/transcriptions/_transcription.html.erb
<tr>
  <td style="width: 150px"><img src="<%= transcription.get_image_url %>" width="450" height="150"></td>
  <td style="width: 99%">
  	<p><%= transcription.transcription %></p>
  	<table class="table table-striped" style="display: block;height: 120px;overflow-y: scroll;">
  	    <%= render transcription.submissions %>
  	</table>
  </td>
  <td>
  	<%= link_to transcription.status(), lock_transcription_path(transcription.id), class: "btn btn-primary", style: "width:85px; margin-bottom: 5px;" %>
  	<%= link_to 'Show', transcription, class: "btn btn-primary", style: "width:85px; margin-bottom: 5px;" %>
  	<%= link_to 'Edit', edit_transcription_path(transcription), class: "btn btn-primary", style: "width:85px" %>
  </td>
</tr>

app/views/transcriptions/edit.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center"><%= @transcription.question.question %></h1>

<img src="<%= @transcription.get_image_url %>" height="200" width="600" style="display: block;margin: 0 auto;">
<br>

<%= render 'form', transcription: @transcription %>

<%= link_to 'Back', transcriptions_path %>

app/views/transcriptions/index.html.erb
<h1 class="text-center">Transcriptions</h1>

<div class="digg_pagination text-center">
  <div class="page_info">
    <%= page_entries_info @posts %>
  </div>
  <%= will_paginate @transcriptions, :container => false %>
</div>
<table class="table table-striped">
  <tbody>
    <%= render @transcriptions %>
  </tbody>
</table>
<div class="text-center"><%= will_paginate %></div>

app/views/transcriptions/show.html.erb
<h1 class="text-center"><%= @transcription.question.question %></h1>

<img src="<%= @transcription.get_image_url %>" height="200" width="600" style="display: block;margin: 0 auto;">

<br>
<p class="text-center"><%= @transcription.transcription %></p>
<br>


  <div class="row">
    <div class="col-md-9">
    <table class="table table-striped">
      <tbody>
        <%= render @transcription.submissions %>
      </tbody>
    </table>
    </div>
    <div class="col-md-3">
    <table class="table table-striped">
      <tbody>
        <% for tag in @transcription.tags do %>
        <tr><td><%= tag.page.title %></td></tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>




<%= link_to 'Edit', edit_transcription_path(@transcription) %> |
<%= link_to 'Back', transcriptions_path %>