config/routes.rb
Rails.application.routes.draw do

  root to: 'geomancer#index'
  constraints(question_id: /[1-9]|1[0-9]|2[0-5]/) do
    get '/:question_id/', to: 'geomancer#question'
    constraints(rolls: /[1-4]{16}/) do
      get '/:question_id/:rolls',   to: 'geomancer#result'
      post '/:question_id/:rolls',  to: 'geomancer#create'
    end
  end
  
  scope '/about' do
    get '/:slug', to: 'static#pages', as: 'topic'
  end

  scope '/admin' do
    resources :pages
    resources :questions, only: [:index, :show] do  
      member do
        get 'lock'
      end
    end
    resources :tags, only: [:create, :update, :destroy]
    resources :transcriptions,  only: [:edit, :index, :show, :update] do
      member do
        get 'lock'
      end
    end
    resources :submissions, only: [:create, :index, :destroy] do
      member do
        get 'select'
      end
    end
    resources :users, only: [:new, :create, :index, :destroy, :edit, :update]
  end

  get    '/about',  to: 'static#about'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :tags, dependent: :destroy
  has_many :resources
end

app/models/pattern.rb
class Pattern < ApplicationRecord
	has_many :transcriptions
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :transcriptions

	def status
		if ENV["BOF_MODE"] != "CROWD_SOURCE" then
			return "Frozen"
		elsif self.locked then
			return "Unfreeze"
		else
			return "Freeze"
		end
	end

	def submissions_allowed?
		if ENV["BOF_MODE"] == "CROWD_SOURCE"  && !self.locked then
			return true
		end
		return false
	end

	def toggle
		if ENV["BOF_MODE"] == "CROWD_SOURCE" then
			self.locked = !self.locked
		end
	end
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :transcription
  
  self.per_page = 10

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :transcription
  belongs_to :page

  validates_uniqueness_of :page_id, scope: :transcription_id
end

app/models/transcription.rb
class Transcription < ApplicationRecord
  belongs_to :question
  belongs_to :pattern
  has_many :submissions
  has_many :tags

  accepts_nested_attributes_for :tags, :reject_if => lambda { |a| a[:page_id].blank? }

  self.per_page = 16

  def get_image_url
    aws_link = "https://s3.amazonaws.com/book-of-fate/images/answers";
    q = (self.question.id - 1).to_s.rjust(2, "0");
    p = self.pattern
    return aws_link + "/q" + q + "/q" + q + "_p" + p.page + "_" + p.side + "_" + p.offset + ".jpg"
  end

  def status
    if !self.question.submissions_allowed? then
      return "Frozen"
    elsif self.locked then
      return "Unfreeze"
    else
      return "Freeze"
    end
  end

  def submissions_allowed?
    return self.question.submissions_allowed? && !self.locked
  end

  def toggle
    if self.question.submissions_allowed? then
      self.locked = !self.locked
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/tags_controller.rb
class TagsController < AdminController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_back(fallback_location: root_path)
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        redirect_to @tag, notice: 'Tag was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:transcription_id, :page_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geomancer_helper.rb
module GeomancerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header_admin.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="/">Book of Fate</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Questions', questions_path %></li>
        <li><%= link_to 'Transcriptions', transcriptions_path %></li>
        <li><%= link_to 'Submissions', submissions_path %></li>
        <li><%= link_to 'Pages', pages_path %></li>              
        <li><%= link_to 'Users', users_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><a><span class="glyphicon glyphicon-user"></span> <%= current_user.email %></a></li>
          <li>
              <%= link_to raw("<span class='glyphicon glyphicon-log-out'></span> Logout"), logout_path, method: "delete" %> 
          </li>
        <% else %>
          <li>
            <%= link_to raw("<span class='glyphicon glyphicon-log-in'></span> Login"), login_path %>  
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <br><br><br><br>
</header>

app/views/layouts/_header_public.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-dropdown">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="/">Book of Fate</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="http://library.miami.edu">Otto G. Richter Library</a></li>
        <li><a href="http://library.miami.edu/specialcollections/">Dept. of Special Collections</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right nav-dropdown">
        <li><%= link_to 'About', about_path %></li>
        <li class="nav-item dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" >Topics<b class="caret"></b>
            <ul class="dropdown-menu">
              <% for topic in @topics %>
                <li><%= link_to topic.title, topic_path(topic.slug), class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_public.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-dropdown">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="/">Book of Fate</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="#">Otto G. Richter Library</a></li>
        <li><a href="#">Dept. of Special Collections</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right nav-dropdown">
        <li><%= link_to 'About', about_path %></li>
        <li class="nav-item dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" >Topics<b class="caret"></b>
            <ul class="dropdown-menu">
              <% for topic in @topics %>
                <li><%= link_to topic.title, topic_path(topic.slug), class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </a>
        </li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book of Fate</title>
    <%= csrf_meta_tags %>
	<%= javascript_include_tag "application" %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <!-- Last compiled and minified JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'layouts/header_admin' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      
      <%= yield %> 
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookOfFate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/geomancer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book of Fate</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <!-- Last compiled and minified JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track': 'reload' %>
    <%= yield(:twitter) %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header_public' %>
      <br><br>
    </header>
    <div class="container-fluid">
      <div class="row">
        <p><%= flash[:notice] %></p>
        <h1 id='title'>choose a question</h1>
      </div>
      <div id='question' class="row">
        <div class="col-xs-2"></div>
        <div class="col-xs-8 question">
          <%= yield(:question) %>
        </div>
        <div class="col-xs-2"></div>
      </div>
      <br>
      <div class="row">
        <div id='geomancer' class='col-xs-6 text-center'>
              <%= yield(:geomancer) %>
        </div>
        <div id='results' class='col-xs-6 text-center'>
              <%= yield(:results) %>
        </div>
      </div>
      <div id='your-fortune' class="row">
        <div id='pattern' class='col-xs-6'>
          <%= yield(:pattern) %>
        </div>
        <div id='fortune-box' class='col-xs-6 fill'>
          <%= yield(:fortune) %>
        </div>
      </div>
      &nbsp;
      <div class="row">
        <div id="transcription-box" class="center-div2 col-xs-12">
          <%= yield(:transcription) %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book of Fate</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <!-- Last compiled and minified JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track': 'reload' %>
    <%= yield(:twitter) %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header_public' %>
      <br><br>
    </header>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <br>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :slug, class: "form-control" %>
  </div>
  <br>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, size: '30x12', class: "form-control" %>
  </div>
  <br>

  <div class="actions text-center">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1 class="text-center">Edit Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1 class="text-center">Pages</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.slug %></td>
        <td><%= page.description %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1 class="text-center">New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<h1 class="text-center"><%= @page.title %></h1>
<h3 class="text-center">(<%= @page.slug %>)</h3>

<div class="text-center">
  <%= simple_format(@page.description) %>
</div>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>